export const currentSkillList = [
    "JavaScript ES6+",
    "React",
    "React Hooks",
    "React Router",
    "JSX",
    "TypeScript",
    "TanStack (ReactQuery)",
    "Redux (Toolkit)",
    "Redux Saga",
    "Git & GitHub",
    "Working with API (fetch, axios)",
    "CSS BEM convention",
    "CSS Flexbox & Grid",
    "Responsive Web Design",
    "NPM",
    "Semantic and accessible HTML",
    "Markdown",
    "Error Handling",
    "Scrum",
    "Trello",
    "Figma",
    "Teamwork",
];